/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { LiskButtonSend as LiskButtonSend } from './components/lisk-buttons/lisk-button-send';

interface HTMLLiskButtonSendElement extends LiskButtonSend, HTMLElement {
}
declare var HTMLLiskButtonSendElement: {
  prototype: HTMLLiskButtonSendElement;
  new (): HTMLLiskButtonSendElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "lisk-button-send": HTMLLiskButtonSendElement;
  }
  interface ElementTagNameMap {
      "lisk-button-send": HTMLLiskButtonSendElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "lisk-button-send": JSXElements.LiskButtonSendAttributes;
      }
  }
  namespace JSXElements {
      export interface LiskButtonSendAttributes extends HTMLAttributes {
        
          amount?: number,
          recipient?: string,
          title?: string
      }
  }
}

import { LiskButtonVote as LiskButtonVote } from './components/lisk-buttons/lisk-button-vote';

interface HTMLLiskButtonVoteElement extends LiskButtonVote, HTMLElement {
}
declare var HTMLLiskButtonVoteElement: {
  prototype: HTMLLiskButtonVoteElement;
  new (): HTMLLiskButtonVoteElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "lisk-button-vote": HTMLLiskButtonVoteElement;
  }
  interface ElementTagNameMap {
      "lisk-button-vote": HTMLLiskButtonVoteElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "lisk-button-vote": JSXElements.LiskButtonVoteAttributes;
      }
  }
  namespace JSXElements {
      export interface LiskButtonVoteAttributes extends HTMLAttributes {
        
          unvotes?: string,
          votes?: string,
          title?: string
      }
  }
}

